[package]
name = "yaro"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
bitflags = "2.9.1"
fdt = "0.1.5"
spin = "0.10.0"
talc = "4.4.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
